import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";
import { AppContainer } from "@/components/structure/Providers";
import AccountModal from "@/components/modals/AccountModal/AccountModal";
import PlanModal from "@/components/modals/PlanModal/PlanModal";
import AddSubjectModal from "@/components/modals/AddSubjectModal/AddSubjectModal";
import CreateGroupModal from "@/components/modals/CreateGroupModal/CreateGroupModal";
import SearchUsersModal from "@/components/modals/SearchUsersModal/SearchUsersModal";
import JoinGroupModal from "@/components/modals/JoinGroupModal/JoinGroupModal";
import { Suspense } from "react";

import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
import "react-calendar-heatmap/dist/styles.css";
import "react-tooltip/dist/react-tooltip.css";
import "react-vertical-timeline-component/style.min.css";
import "react-loading-skeleton/dist/skeleton.css";
import ChatModal from "@/components/modals/ChatModal/ChatModal";
import SubjectsModal from "@/components/modals/SubjectsModal/SubjectsModal";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable}`}>
        <Suspense>
          <AppContainer>
            {/* <PlanModal />
          <ChatModal /> */}
            <AccountModal />
            <PlanModal />
            <AddSubjectModal />
            <SearchUsersModal />
            <CreateGroupModal />
            <JoinGroupModal />
            <ChatModal />
            <SubjectsModal />
            {/* <JoinGroupModal />
          <AddSubjectModal />
          <SubjectsModal />
          <SearchUsersModal />
          <EditGroupModal />
          <WelcomeModal /> */}
            {children}
          </AppContainer>
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            transition={Bounce}
            style={{ zIndex: 10000000 }}
          />
        </Suspense>
      </body>
    </html>
  );
}
