import { Roboto } from "next/font/google";
import "./globals.css";
import { Bounce, ToastContainer } from "react-toastify";
import { AppContainer } from "@/components/structure/Providers";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        <AppContainer>
          {/* <PlanModal />
            <ChatModal />
            <AccountModal />
            <JoinGroupModal />
            <AddSubjectModal />
            <SubjectsModal />
            <SearchUsersModal />
            <EditGroupModal />
            <WelcomeModal /> */}
          {children}
        </AppContainer>
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
          style={{ zIndex: 10000000 }}
        />
      </body>
    </html>
  );
}
